version: 2
jobs:
     build:
        working_directory: ~/color-app
        docker:
            - image: circleci/golang:1.9.2
        steps:
            - checkout
            - run:
                name: Build color-app binary
                command: go build ./app/hello-color.go
     deploy:
       staging:
         branch: master
         codedeploy:
             app:
              application_root: /
              revision_location:
                revision_type: S3
                s3_location:
                  bucket: blue-green-bucket
                  key_pattern: hello-color-app-{BRANCH}-{SHORT_COMMIT}
              region: us-east-1
              deployment_group: hello-color-deployment       
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deployment