version: 2
jobs:
    deployment:
      staging:
       branch: master
        codedeploy:
        circleci-demo-app:
        application_root: /
        region: us-east-1
         revision_location:
           revision_type: S3
           s3_location:
             bucket: blue-green-bucket
             key_pattern: hello-color-app-{BRANCH}-{SHORT_COMMIT}
           deployment_group: hello-color-deployment
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deployment          