version: 2
jobs:
     build:
        working_directory: ~/color-app
        docker:
            - image: circleci/golang:1.9.2
        steps:
            - checkout
            - run:
                name: Build color-app binary
                command: go build ./app/hello-color.go
            - run:
                name: Install aws cli
                command:
                    sudo apt-get -y update && sudo apt-get install -y awscli --fix-missing
            - run:
                name: Zip and Push Artifact to s3
                command: aws --region us-east-1 deploy push --application-name aldebran-dev --s3-location s3://blue-green-bucket/color-app
            - run:
                name: Deploy the binary
                command: aws --region us-east-1 deploy create-deployment --application-name aldebran-dev --deployment-group-name aldebran-deployment_group-dev  --s3-location "bucket=blue-green-bucket,key=color-app,bundleType=zip"                                    
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build