version: 2
jobs:
     build:
        working_directory: ~/color-app
        docker:
            - image: circleci/golang:1.9.2
        steps:
            - checkout
            - run:
                name: Build color-app binary
                command: go build app/hello-color.go
    deployment:
      staging:
       branch: master
        codedeploy:
        circleci-demo-app:
        application_root: /
        region: us-east-1
         revision_location:
           revision_type: S3
           s3_location:
             bucket: blue-green-bucket
             key_pattern: hello-color-app-{BRANCH}-{SHORT_COMMIT}
           deployment_group: hello-color-deployment
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deployment          