version: 2
jobs:
     build:
        working_directory: ~/color-app
        docker:
            - image: circleci/golang:1.9.2
        steps:
            - checkout
            - run:
                name: Build color-app binary
                command: go build ./app/hello-color.go
            - run:
                name: Install aws cli
                command:
                    sudp apt-get -y update && sudo apt-get install -y awscli --fix-missing
            - run:
                name: Zip and Push Artifact to s3
                command: aws --region us-east-1 deploy push --application-name hello-color --s3-location s3://blue-green-bucket
            - run:
                name: Deploy the binary
                command: aws --region us-east-1 deploy create-deployment \
                             --application-name "hello-color" \
                             --deployment-group-name "hello-color-deployment" \
                             --s3-location "bucket=blue-green-bucket,key=${hello-color-app-{BRANCH}-{SHORT_COMMIT}},bundleType=zip"     
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build